openapi: 3.0.0
info:
  title: Open-Meteo API
  version: 1.0.0
  description: API for accessing weather forecasts.
servers:
  - url: https://api.open-meteo.com/v1/forecast
paths:
  /:
    get:
      summary: Get hourly weather data
      description: Retrieve hourly weather data including temperature, rain, showers, and snowfall.
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of the location.
          schema:
            type: number
            format: float
        - name: longitude
          in: query
          required: true
          description: Longitude of the location.
          schema:
            type: number
            format: float
        - name: hourly
          in: query
          required: true
          description: Comma-separated list of hourly weather data types to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with hourly weather data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature_2m:
                    type: array
                    items:
                      type: number
                  rain:
                    type: array
                    items:
                      type: number
                  showers:
                    type: array
                    items:
                      type: number
                  snowfall:
                    type: array
                    items:
                      type: number
        '400':
          description: Bad request - invalid parameters.
        '500':
          description: Internal server error.
